site_name: Atomix
theme:
  name: material
  palette:
    # Dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - Getting Started: getting-started/introduction.md

  - Architecture:
    - Introduction: architecture/introduction.md
    - Data Table: architecture/data_table.md
    - Memory management: architecture/mem_management.md

  - Internals:
    - Introduction: internals/introduction.md
    - Data:
      - Data Type: internals/data/data_type.md
      - Column: internals/data/column.md
      - Data Table: internals/data/data_table.md
    - Memory:
      - Buffer: internals/mem/buffer.md
      - Aligned allocator: internals/mem/aligned_allocator.md
      - Virtual memory: internals/mem/vmem.md
      - Mem route: internals/mem/mem_route.md

  - Architecture Decision Records:
      - ADR-0001: adr/adr-0001-shared_ownership_buffer.md
      - ADR-0002: adr/adr-0002-chunked_column_storage.md
      - ADR-0003: adr/adr-0003-removal_vmem_chunk.md

  - Benchmarks:
    - Memory allocation strategies: benchmarks/memory_allocation_performance.md

  - Future features:
    - Introduction: future_features/introduction.md
    - Proposals:
      - Custom allocator: future_features/proposals/custom_allocator.md
      - IO: future_features/proposals/io.md
      - Parallelism: future_features/proposals/parallelism.md

  - Contributing:
    - Introduction: contributing/introduction.md
    - Project structure: contributing/project_structure.md
    - Communication: contributing/communication.md
    - Development workflow: contributing/development_workflow.md
    - ADR: contributing/arquitecture_adr.md
    - Benchmarks: contributing/benchmark.md